select = ["ALL"]
ignore = ["ANN101", "ANN102", "D203", "D211", "D212", "D213", "UP009", "S101", "S314", "INP001", "FLY002", "TD002", "TD003", "DTZ007", "FA102", "PERF203", "FIX002"]

exclude = ["docs"]
